insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(101,'HCL',700.25);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(102,'Infosys',950.25);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(103,'BHEL',40.85);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(104,'Ineuron',71.50);