insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,STOCK_PRICE)values(101,'Hcl',399.9)
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,STOCK_PRICE)values(103,'adani',3444.3)
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,STOCK_PRICE)values(104,'Ineuron',999.3)