package in.ineuron.model;
// Generated 16-Mar-2023, 10:21:15 pm by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "demo")
public class Employee implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer eid;
	private String ename;
	private Integer eage;
	private String eaddr;

	public Employee() {
	}

	public Employee(String ename, Integer eage, String eaddr) {
		this.ename = ename;
		this.eage = eage;
		this.eaddr = eaddr;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "eid", unique = true, nullable = false)
	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	@Column(name = "ename", length = 20)
	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	@Column(name = "eage")
	public Integer getEage() {
		return this.eage;
	}

	public void setEage(Integer eage) {
		this.eage = eage;
	}

	@Column(name = "eaddr", length = 20)
	public String getEaddr() {
		return this.eaddr;
	}

	public void setEaddr(String eaddr) {
		this.eaddr = eaddr;
	}

	@Override
	public String toString() {
		return "Employee [eid=" + eid + ", ename=" + ename + ", eage=" + eage + ", eaddr=" + eaddr + "]";
	}

}
